#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLinqeToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CemProDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CemProDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CUST_ID;
		
		private string _CUST_CODE;
		
		private string _CUST_NAME;
		
		private string _CUST_ADDRESS;
		
		private string _CUST_PHONE;
		
		private int _CUST_CREATEDBY;
		
		private System.DateTime _CUST_CREATEDDT;
		
		private string _CUST_ISACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUST_IDChanging(int value);
    partial void OnCUST_IDChanged();
    partial void OnCUST_CODEChanging(string value);
    partial void OnCUST_CODEChanged();
    partial void OnCUST_NAMEChanging(string value);
    partial void OnCUST_NAMEChanged();
    partial void OnCUST_ADDRESSChanging(string value);
    partial void OnCUST_ADDRESSChanged();
    partial void OnCUST_PHONEChanging(string value);
    partial void OnCUST_PHONEChanged();
    partial void OnCUST_CREATEDBYChanging(int value);
    partial void OnCUST_CREATEDBYChanged();
    partial void OnCUST_CREATEDDTChanging(System.DateTime value);
    partial void OnCUST_CREATEDDTChanged();
    partial void OnCUST_ISACTIVEChanging(string value);
    partial void OnCUST_ISACTIVEChanged();
    #endregion
		
		public CUSTOMER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CUST_ID
		{
			get
			{
				return this._CUST_ID;
			}
			set
			{
				if ((this._CUST_ID != value))
				{
					this.OnCUST_IDChanging(value);
					this.SendPropertyChanging();
					this._CUST_ID = value;
					this.SendPropertyChanged("CUST_ID");
					this.OnCUST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUST_CODE
		{
			get
			{
				return this._CUST_CODE;
			}
			set
			{
				if ((this._CUST_CODE != value))
				{
					this.OnCUST_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUST_CODE = value;
					this.SendPropertyChanged("CUST_CODE");
					this.OnCUST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CUST_NAME
		{
			get
			{
				return this._CUST_NAME;
			}
			set
			{
				if ((this._CUST_NAME != value))
				{
					this.OnCUST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUST_NAME = value;
					this.SendPropertyChanged("CUST_NAME");
					this.OnCUST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ADDRESS", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string CUST_ADDRESS
		{
			get
			{
				return this._CUST_ADDRESS;
			}
			set
			{
				if ((this._CUST_ADDRESS != value))
				{
					this.OnCUST_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._CUST_ADDRESS = value;
					this.SendPropertyChanged("CUST_ADDRESS");
					this.OnCUST_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_PHONE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CUST_PHONE
		{
			get
			{
				return this._CUST_PHONE;
			}
			set
			{
				if ((this._CUST_PHONE != value))
				{
					this.OnCUST_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CUST_PHONE = value;
					this.SendPropertyChanged("CUST_PHONE");
					this.OnCUST_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_CREATEDBY", DbType="Int NOT NULL")]
		public int CUST_CREATEDBY
		{
			get
			{
				return this._CUST_CREATEDBY;
			}
			set
			{
				if ((this._CUST_CREATEDBY != value))
				{
					this.OnCUST_CREATEDBYChanging(value);
					this.SendPropertyChanging();
					this._CUST_CREATEDBY = value;
					this.SendPropertyChanged("CUST_CREATEDBY");
					this.OnCUST_CREATEDBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_CREATEDDT", DbType="DateTime NOT NULL")]
		public System.DateTime CUST_CREATEDDT
		{
			get
			{
				return this._CUST_CREATEDDT;
			}
			set
			{
				if ((this._CUST_CREATEDDT != value))
				{
					this.OnCUST_CREATEDDTChanging(value);
					this.SendPropertyChanging();
					this._CUST_CREATEDDT = value;
					this.SendPropertyChanged("CUST_CREATEDDT");
					this.OnCUST_CREATEDDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_ISACTIVE", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string CUST_ISACTIVE
		{
			get
			{
				return this._CUST_ISACTIVE;
			}
			set
			{
				if ((this._CUST_ISACTIVE != value))
				{
					this.OnCUST_ISACTIVEChanging(value);
					this.SendPropertyChanging();
					this._CUST_ISACTIVE = value;
					this.SendPropertyChanged("CUST_ISACTIVE");
					this.OnCUST_ISACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
