//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLinqeToSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public int SUPP_ID { get; set; }
        public string SUPP_CODE { get; set; }
        public string SUPP_NAME { get; set; }
        public string SUPP_ADDRESS { get; set; }
        public string SUPP_PHONE { get; set; }
        public string SUPP_TYPE { get; set; }
        public int SUPP_CREATEDBY { get; set; }
        public System.DateTime SUPP_CREATEDDT { get; set; }
        public string SUPP_ISACTIVE { get; set; }
    }
}
